name: 'Terraform Plan'

# Allow run manually
on:
  workflow_dispatch:


jobs:
  azure-terraform-job:
    name: 'Terraform Build'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Tfenv
        id: install-tfenv
        run: |
          brew install tfenv

