name: 'Terraform Plan'

# Allow run manually
on:
  workflow_dispatch:


jobs:
  azure-terraform-job:
    name: 'Terraform Build'
    runs-on: ubuntu-latest
    env:
      terraform-version: "1.5.5"
      terraform-workspace: "prd"
      checkov-skipped-tests: ""
      terraform-compliance-policy-path: ""
      ARM_CLIENT_ID: ${{ secrets.SpokeSvpClientId }}
      ARM_CLIENT_SECRET: ${{ secrets.SpokeSvpClientSecret }}
      ARM_TENANT_ID: ${{ secrets.SpokeTenantId }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SpokeSubId }}
      ARM_USE_AZUREAD: true

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Tfenv
        id: install-packages
        run: |
          brew install tfenv tfsec

      - name: Setup Tfenv
        id: setup-tfenv
        run: |
          tfenv install ${{ env.terraform-version }} && tfenv use ${{ env.terraform-version }}

      - name: Terraform Init
        id: terraform init
        run: |
          terraform workspace select ${{ env.terraform-workspace }} || terraform workspace ${{ env.terraform-workspace }} && \
          terraform init && \
          terraform validate && \
          terraform plan -out tfplan

      - name: terraform-compliance
        id: terraform-compliance-check
        uses: terraform-compliance/github_action@0.3.0
        with:
          plan: "tfplan"
          features: https://github.com/libre-devops/azure-naming-convention.git//?ref=main
